services:
  mongo:
    image: mongo:latest
    container_name: mongo-dev
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: taskflowadmin
      MONGO_INITDB_ROOT_PASSWORD: TaskFlow123
    volumes:
      - mongo-data-dev:/data/db
    networks:
      - taskflow-net-dev

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-dev
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: taskflowadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: TaskFlow123
      ME_CONFIG_MONGODB_URL: mongodb://taskflowadmin:TaskFlow123@mongo:27017/
      ME_CONFIG_BASICAUTH: "true"
    depends_on:
      - mongo
    networks:
      - taskflow-net-dev

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: taskflow-server-dev
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://taskflowadmin:TaskFlow123@mongo:27017/taskflow?authSource=admin
      - NODE_ENV=development
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - taskflow-net-dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: taskflow-client-dev
    restart: always
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - taskflow-net-dev

volumes:
  mongo-data-dev:

networks:
  taskflow-net-dev:
    driver: bridge
