services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: taskflowadmin
      MONGO_INITDB_ROOT_PASSWORD: TaskFlow123
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: taskflowadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: TaskFlow123
      ME_CONFIG_MONGODB_URL: mongodb://taskflowadmin:TaskFlow123@mongo:27017/
      ME_CONFIG_BASICAUTH: "true"
    depends_on:
      - mongo

volumes:
  mongo-data:
